# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb96f92284ae8124883820302943e435b0a0f48e5fa9809949ea030ed00c4a1b06ec723754e33fedbb05c1f26a3a0fffbd180efc4b57978149c2c3c10deba96d

test:
  secret_key_base: 0052cfd40d121e45b50692afdd9a442ff7b33af9c15f2a6735983745b1cc9e51895c1a6fe0370b289e3d5b0a16f82f8f6540cae2a8c0e986a95ec5970df8f556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
